#include "AnisotropicSurfaceMesh.h"
#include "MarchingCubesTables.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <unordered_map>

namespace Frontier::ProjectFluid {
namespace {
Vec3 Cross(Vec3 a,Vec3 b){return{a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
float AxisLength(const SurfaceKernel& k){return std::max({Length(k.AxisA),Length(k.AxisB),Length(k.AxisC)});}
constexpr int Corner[8][3]={{0,0,0},{1,0,0},{1,1,0},{0,1,0},{0,0,1},{1,0,1},{1,1,1},{0,1,1}};
constexpr int EdgeCorners[12][2]={{0,1},{1,2},{2,3},{3,0},{4,5},{5,6},{6,7},{7,4},{0,4},{1,5},{2,6},{3,7}};
}

Vec3 AnisotropicSurfaceMesh::GridPosition(int x,int y,int z) noexcept{return{MinX+x*Spacing,MinY+y*Spacing,MinZ+z*Spacing};}
std::size_t AnisotropicSurfaceMesh::At(int x,int y,int z)const noexcept{return(static_cast<std::size_t>(z)*Ny+y)*Nx+x;}
float AnisotropicSurfaceMesh::Evaluate(Vec3 point,const std::vector<SurfaceKernel>& kernels)const noexcept{float field=0;for(const auto& k:kernels){const Vec3 r=point-k.Centre;const float aa=std::max(Dot(k.AxisA,k.AxisA),1e-10f),bb=std::max(Dot(k.AxisB,k.AxisB),1e-10f),cc=std::max(Dot(k.AxisC,k.AxisC),1e-10f);const float u=Dot(r,k.AxisA)/aa,v=Dot(r,k.AxisB)/bb,w=Dot(r,k.AxisC)/cc,q2=u*u+v*v+w*w;if(q2<1){const float q=1-q2;field+=k.VolumeWeight*q*q*q;}}return field;}
Vec3 AnisotropicSurfaceMesh::Gradient(Vec3 point)const noexcept{const int x=std::clamp(static_cast<int>(std::round((point.x-MinX)/Spacing)),1,Nx-2),y=std::clamp(static_cast<int>(std::round((point.y-MinY)/Spacing)),1,Ny-2),z=std::clamp(static_cast<int>(std::round((point.z-MinZ)/Spacing)),1,Nz-2);return{(Field_[At(x+1,y,z)]-Field_[At(x-1,y,z)])/(2*Spacing),(Field_[At(x,y+1,z)]-Field_[At(x,y-1,z)])/(2*Spacing),(Field_[At(x,y,z+1)]-Field_[At(x,y,z-1)])/(2*Spacing)};}
void AnisotropicSurfaceMesh::MarkKernel(const SurfaceKernel& k,std::vector<std::uint8_t>& dirty)const{const float radius=AxisLength(k)+2*Spacing;int x0=std::clamp(static_cast<int>((k.Centre.x-radius-MinX)/Spacing)/Brick-1,0,Bx-1),x1=std::clamp(static_cast<int>((k.Centre.x+radius-MinX)/Spacing)/Brick+1,0,Bx-1),y0=std::clamp(static_cast<int>((k.Centre.y-radius-MinY)/Spacing)/Brick-1,0,By-1),y1=std::clamp(static_cast<int>((k.Centre.y+radius-MinY)/Spacing)/Brick+1,0,By-1),z0=std::clamp(static_cast<int>((k.Centre.z-radius-MinZ)/Spacing)/Brick-1,0,Bz-1),z1=std::clamp(static_cast<int>((k.Centre.z+radius-MinZ)/Spacing)/Brick+1,0,Bz-1);for(int z=z0;z<=z1;++z)for(int y=y0;y<=y1;++y)for(int x=x0;x<=x1;++x)dirty[(z*By+y)*Bx+x]=1;}
void AnisotropicSurfaceMesh::RebuildFieldBrick(int bx,int by,int bz,const std::vector<SurfaceKernel>& kernels){const int x0=bx*Brick,x1=std::min(Nx-1,(bx+1)*Brick),y0=by*Brick,y1=std::min(Ny-1,(by+1)*Brick),z0=bz*Brick,z1=std::min(Nz-1,(bz+1)*Brick);for(int z=z0;z<=z1;++z)for(int y=y0;y<=y1;++y)for(int x=x0;x<=x1;++x)Field_[At(x,y,z)]=Evaluate(GridPosition(x,y,z),kernels);}
void AnisotropicSurfaceMesh::RebuildMeshBrick(int bx,int by,int bz){Chunk& chunk=Chunks_[(bz*By+by)*Bx+bx];chunk.TriangleVertices.clear();const int x1=std::min(Nx-1,(bx+1)*Brick),y1=std::min(Ny-1,(by+1)*Brick),z1=std::min(Nz-1,(bz+1)*Brick);for(int z=bz*Brick;z<z1;++z)for(int y=by*Brick;y<y1;++y)for(int x=bx*Brick;x<x1;++x){std::array<Vec3,8> p{};std::array<float,8> value{};int cube=0;for(int c=0;c<8;++c){p[c]=GridPosition(x+Corner[c][0],y+Corner[c][1],z+Corner[c][2]);value[c]=Field_[At(x+Corner[c][0],y+Corner[c][1],z+Corner[c][2])];if(value[c]>=IsoValue_)cube|=1<<c;}const auto mask=MarchingCubesTables::Edge[cube];if(!mask)continue;std::array<EdgeVertex,12> edge{};for(int e=0;e<12;++e)if(mask&(1<<e)){const int a=EdgeCorners[e][0],b=EdgeCorners[e][1];const float denominator=value[b]-value[a],t=std::abs(denominator)>1e-8f?std::clamp((IsoValue_-value[a])/denominator,0.0f,1.0f):.5f;const auto na=static_cast<std::uint32_t>(At(x+Corner[a][0],y+Corner[a][1],z+Corner[a][2])),nb=static_cast<std::uint32_t>(At(x+Corner[b][0],y+Corner[b][1],z+Corner[b][2])),lo=std::min(na,nb),hi=std::max(na,nb);edge[e]={p[a]+(p[b]-p[a])*t,(static_cast<std::uint64_t>(lo)<<32)|hi};}const int offset=cube*16;for(int t=0;t<16&&MarchingCubesTables::Tri[offset+t]>=0;t+=3){chunk.TriangleVertices.push_back(edge[MarchingCubesTables::Tri[offset+t]]);chunk.TriangleVertices.push_back(edge[MarchingCubesTables::Tri[offset+t+1]]);chunk.TriangleVertices.push_back(edge[MarchingCubesTables::Tri[offset+t+2]]);}}}
void AnisotropicSurfaceMesh::AssembleAndSmooth(){Mesh_={};std::unordered_map<std::uint64_t,std::uint32_t>weld;for(const Chunk& chunk:Chunks_)for(const EdgeVertex& vertex:chunk.TriangleVertices){auto [it,inserted]=weld.emplace(vertex.EdgeKey,static_cast<std::uint32_t>(Mesh_.Vertices.size()));if(inserted)Mesh_.Vertices.push_back({vertex.Position,{}});Mesh_.Indices.push_back(it->second);}if(Mesh_.Indices.empty()){OpenEdgeCount_=0;NonManifoldEdgeCount_=0;return;}std::unordered_map<std::uint64_t,std::uint32_t> edgeUse;for(std::size_t i=0;i<Mesh_.Indices.size();i+=3)for(int e=0;e<3;++e){std::uint32_t a=Mesh_.Indices[i+e],b=Mesh_.Indices[i+(e+1)%3];if(a>b)std::swap(a,b);++edgeUse[(static_cast<std::uint64_t>(a)<<32)|b];}OpenEdgeCount_=0;NonManifoldEdgeCount_=0;for(const auto& [edge,uses]:edgeUse){(void)edge;if(uses==1)++OpenEdgeCount_;else if(uses!=2)++NonManifoldEdgeCount_;}
    std::vector<std::vector<std::uint32_t>> adjacent(Mesh_.Vertices.size());for(std::size_t i=0;i<Mesh_.Indices.size();i+=3)for(int e=0;e<3;++e){const auto a=Mesh_.Indices[i+e],b=Mesh_.Indices[i+(e+1)%3];adjacent[a].push_back(b);adjacent[b].push_back(a);}auto volume=[&](){double result=0;for(std::size_t i=0;i<Mesh_.Indices.size();i+=3){const Vec3 a=Mesh_.Vertices[Mesh_.Indices[i]].Position,b=Mesh_.Vertices[Mesh_.Indices[i+1]].Position,c=Mesh_.Vertices[Mesh_.Indices[i+2]].Position;result+=Dot(a,Cross(b,c))/6.0;}return std::abs(result);};const double originalVolume=volume();Vec3 centroid{};for(const auto& v:Mesh_.Vertices)centroid+=v.Position;centroid=centroid/static_cast<float>(Mesh_.Vertices.size());
    auto laplace=[&](float amount){std::vector<Vec3> next(Mesh_.Vertices.size());for(std::size_t i=0;i<next.size();++i){if(adjacent[i].empty()){next[i]=Mesh_.Vertices[i].Position;continue;}Vec3 average{};for(auto j:adjacent[i])average+=Mesh_.Vertices[j].Position;average=average/static_cast<float>(adjacent[i].size());next[i]=Mesh_.Vertices[i].Position+(average-Mesh_.Vertices[i].Position)*amount;}for(std::size_t i=0;i<next.size();++i)Mesh_.Vertices[i].Position=next[i];};laplace(.18f);laplace(-.19f);const double smoothedVolume=volume();if(originalVolume>1e-12&&smoothedVolume>1e-12){const float scale=static_cast<float>(std::cbrt(originalVolume/smoothedVolume));for(auto& v:Mesh_.Vertices)v.Position=centroid+(v.Position-centroid)*scale;}for(auto& v:Mesh_.Vertices)v.Normal=Normalized(Gradient(v.Position)*-1.0f);
}
bool AnisotropicSurfaceMesh::SaveObj(const std::string& path)const{std::ofstream out(path);if(!out)return false;out<<"# Project Fluid summed anisotropic field / Marching Cubes\n";for(const auto& v:Mesh_.Vertices)out<<"v "<<v.Position.x<<' '<<v.Position.y<<' '<<v.Position.z<<"\nvn "<<v.Normal.x<<' '<<v.Normal.y<<' '<<v.Normal.z<<'\n';for(std::size_t i=0;i<Mesh_.Indices.size();i+=3){const auto a=Mesh_.Indices[i]+1,b=Mesh_.Indices[i+1]+1,c=Mesh_.Indices[i+2]+1;out<<"f "<<a<<"//"<<a<<' '<<b<<"//"<<b<<' '<<c<<"//"<<c<<'\n';}return static_cast<bool>(out);}
void AnisotropicSurfaceMesh::Update(const std::vector<SurfaceKernel>& kernels){std::vector<std::uint8_t> dirty(Bx*By*Bz,0);if(Previous_.size()!=kernels.size())std::fill(dirty.begin(),dirty.end(),1);else for(std::size_t i=0;i<kernels.size();++i){const auto& a=Previous_[i];const auto& b=kernels[i];if(!(a.Centre==b.Centre)||!(a.AxisA==b.AxisA)||!(a.AxisB==b.AxisB)||!(a.AxisC==b.AxisC)||a.VolumeWeight!=b.VolumeWeight){MarkKernel(a,dirty);MarkKernel(b,dirty);}}DirtyBrickCount_=0;for(int bz=0;bz<Bz;++bz)for(int by=0;by<By;++by)for(int bx=0;bx<Bx;++bx)if(dirty[(bz*By+by)*Bx+bx]){++DirtyBrickCount_;RebuildFieldBrick(bx,by,bz,kernels);}for(int bz=0;bz<Bz;++bz)for(int by=0;by<By;++by)for(int bx=0;bx<Bx;++bx)if(dirty[(bz*By+by)*Bx+bx])RebuildMeshBrick(bx,by,bz);Previous_=kernels;if(DirtyBrickCount_==0)return;AssembleAndSmooth();}
}
