import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {createIcons,BookOpen,Download,ScanEye,ArrowLeft,ArrowRight,Grip,Box,Rotate3d,Triangle,GitFork,Focus,Mouse,Pause,Play,SkipBack,X as XIcon,Crosshair} from 'lucide';
import '../style.css';import './crab.css';
import {CrabRig} from './rig.js';import {CrabController,TARGET_RADIUS} from './controller.js';import {CRAB,V} from './anatomy.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={BookOpen,Download,ScanEye,ArrowLeft,ArrowRight,Grip,Box,Rotate3d,Triangle,GitFork,Focus,Mouse,Pause,Play,SkipBack,X:XIcon,Crosshair};const refresh=()=>createIcons({icons,attrs:{'aria-hidden':'true'}});refresh();
const viewport=$('#viewport'),build=new URLSearchParams(location.search).has('build'),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;viewport.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#eef0e9');scene.fog=new THREE.Fog('#eef0e9',.35,.9);
const camera=new THREE.PerspectiveCamera(36,1,.001,4);camera.position.set(.130,.090,.160);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,.015,.009);orbit.enableDamping=true;orbit.minDistance=.035;orbit.maxDistance=.5;orbit.maxPolarAngle=Math.PI*.51;orbit.autoRotateSpeed=.45;
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.05).texture;scene.environmentIntensity=.40;room.dispose();pmrem.dispose();
const sun=new THREE.DirectionalLight('#fff8e8',1.8);sun.position.set(-.13,.20,.13);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-.12,right:.12,top:.13,bottom:-.11,near:.01,far:.6});sun.shadow.bias=-.0002;sun.shadow.normalBias=.00012;sun.shadow.radius=4;scene.add(sun);
const fill=new THREE.DirectionalLight('#dcebf4',.65);fill.position.set(.16,.1,-.08);scene.add(fill,new THREE.HemisphereLight('#eef3df','#a6ad99',.42));
const floor=new THREE.Mesh(new THREE.PlaneGeometry(3,3),new THREE.MeshStandardMaterial({color:'#e6eadd',roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;floor.position.y=-.00002;scene.add(floor);
const grid=new THREE.Mesh(new THREE.PlaneGeometry(.4,.4),new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{travel:{value:0},strength:{value:.03}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float travel;uniform float strength;void main(){vec2 p=(vUv-.5)*400.;p.x+=travel;vec2 a=abs(fract(p/10.-.5)-.5)/fwidth(p/10.);float f=1.-smoothstep(.08,.5,length(vUv-.5));gl_FragColor=vec4(.35,.42,.32,(1.-min(min(a.x,a.y),1.))*strength*f);}'}));grid.rotation.x=-Math.PI/2;grid.position.y=0;scene.add(grid);
const bead=new THREE.Mesh(new THREE.SphereGeometry(TARGET_RADIUS,40,24),new THREE.MeshStandardMaterial({color:'#b99351',roughness:.37,metalness:.10}));bead.castShadow=true;scene.add(bead);
const ring=new THREE.Mesh(new THREE.TorusGeometry(TARGET_RADIUS*1.7,.00009,6,64),new THREE.MeshBasicMaterial({color:'#ab8b50',transparent:true,opacity:.8,depthTest:false,depthWrite:false}));ring.renderOrder=10;scene.add(ring);
const tag=document.createElement('div');tag.className='target-tag';tag.textContent='DRAG TARGET';viewport.append(tag);
let model,clips,rig,controller,mixer,action,skeleton,current='Idle',mode=build?'motion':'grab',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,speed=1,dirty=true,tween=null,walkCycles=0,clock=new THREE.Clock(),lastUI=0,exporting=false,drag=null,toastTimer;const materials=new Set();
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2700);}
function pauseIcon(){for(const id of ['play-button','grab-pause']){$('#'+id).innerHTML=`<i data-lucide="${paused?'play':'pause'}"></i>`;$('#'+id).setAttribute('aria-label',paused?'Resume playback':'Pause playback');}refresh();}
function syncMode(){document.body.classList.toggle('motion-mode',mode==='motion');$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);});bead.visible=ring.visible=mode==='grab';tag.hidden=mode!=='grab';$('#viewport-mode').textContent=mode==='grab'?'PINCER TEST':'ANATOMY STUDY';const hints=$$('.zoom-hint span');hints[0].textContent=mode==='grab'?'Drag bead to move it':'Drag to orbit';hints[1].textContent=mode==='grab'?'Drag elsewhere to orbit':'Scroll to explore';resize();}
function setMode(name){if(!rig||name===mode)return;endDrag();mixer.stopAllAction();rig.reset();mode=name;paused=false;syncMode();if(mode==='grab'){controller.reset();syncFields();}else selectClip(current);setView('perspective');pauseIcon();dirty=true;}
const labels={Idle:['Idle','Eyes, antennae and mouthparts.'],Walk_Left:['Walk left','Lateral gait · tracked ground at 10 mm/s'],Walk_Right:['Walk right','Lateral gait · tracked ground at 10 mm/s'],Pinch_L:['Left pincer','Fixed propodal finger · moving dactylus'],Pinch_R:['Right pincer','Larger crusher claw · one moving finger']};
function selectClip(name){if(!mixer)return;if(mode!=='motion'){mode='motion';endDrag();rig.reset();syncMode();}const clip=clips.find(c=>c.name===name);if(!clip)return;mixer.stopAllAction();current=name;$('#viewport-mode').textContent='ANATOMY STUDY';action=mixer.clipAction(clip).reset();const loop=!name.startsWith('Pinch_');action.setLoop(loop?THREE.LoopRepeat:THREE.LoopOnce,loop?Infinity:1);action.clampWhenFinished=true;action.timeScale=speed;action.play();action.paused=paused;walkCycles=0;$$('[data-clip]').forEach(b=>{b.classList.toggle('active',b.dataset.clip===name);b.setAttribute('aria-pressed',b.dataset.clip===name);});$('#current-clip').textContent=labels[name][0];$('#clip-note').textContent=labels[name][1];$('#clip-type').textContent=loop?'LOOP':'ONE SHOT';$('#scrubber').max=clip.duration;$('#total-time').textContent=clip.duration.toFixed(2).padStart(5,'0');$('.timeline-ticks').innerHTML=Array.from({length:7},(_,i)=>`<span>${Number((clip.duration*i/6).toFixed(1))}${i===6?' s':''}</span>`).join('');pauseIcon();dirty=true;}
async function load(){try{if(build){const {createCrab}=await import('./model.js');const a=createCrab();model=a.root;clips=a.clips;}else{const a=await new GLTFLoader().loadAsync('/models/crab.glb');model=a.scene;clips=a.animations;}scene.add(model);model.updateMatrixWorld(true);let triangles=0,bones=0;model.traverse(o=>{if(o.isBone)bones++;if(o.isMesh){o.castShadow=o.receiveShadow=true;o.frustumCulled=false;materials.add(o.material);triangles+=o.geometry.index.count/3;}});$('#triangles').textContent=`${(triangles/1000).toFixed(1)}k triangles`;$('#bones').textContent=`${bones} joints`;rig=new CrabRig(model);controller=new CrabController(rig);mixer=new THREE.AnimationMixer(model);mixer.addEventListener('loop',e=>{if(e.action===action)walkCycles+=e.loopDelta;});mixer.addEventListener('finished',()=>{if(mode==='motion'){paused=true;pauseIcon();dirty=true;}});skeleton=new THREE.SkeletonHelper(model);skeleton.material.depthTest=false;skeleton.renderOrder=12;skeleton.visible=false;scene.add(skeleton);if(mode==='motion'){syncMode();selectClip('Idle');}else{rig.poseClip('Idle',0);syncMode();syncFields();pauseIcon();}$('#loading').classList.add('hidden');window.crab={model,clips,rig,controller,mixer,renderer,scene,camera,orbit,stats:{triangles,bones},setMode,selectClip,setPaused(v){paused=Boolean(v);pauseIcon();dirty=true;},get mode(){return mode;},poseAt(name,t){paused=true;selectClip(name);action.paused=false;action.time=t;mixer.update(0);action.paused=true;model.updateMatrixWorld(true);renderer.render(scene,camera);dirty=true;},targetScreen,exportGLB};window.crabReady=true;dirty=true;}catch(error){window.crabError=error.message;console.error(error);$('#loading').innerHTML='<span>The crab could not load.</span><small>Please reload the study.</small>';}}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=w<700?48:36;camera.updateProjectionMatrix();dirty=true;}new ResizeObserver(resize).observe(viewport);resize();orbit.addEventListener('change',()=>dirty=true);document.addEventListener('click',()=>dirty=true);document.addEventListener('input',()=>dirty=true);document.addEventListener('visibilitychange',()=>clock.getDelta());
function setView(name){const views={perspective:{p:[.130,.090,.160],t:[0,.015,.009]},front:{p:[0,.052,.24],t:[0,.018,.005]},side:{p:[.24,.069,.012],t:[0,.016,.005]},top:{p:[.001,.255,.001],t:[0,.006,.002]},claw:{p:[.088,.052,.112],t:[.015,.019,.043]}};const v=views[name];if(!v)return;tween={start:performance.now(),p0:camera.position.clone(),p1:V(...v.p),t0:orbit.target.clone(),t1:V(...v.t)};$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));}
function syncFields(){if(!controller)return;for(const key of ['x','y','z']){$('#target-'+key).value=controller.placement[key];$('#value-'+key).textContent=`${controller.placement[key].toFixed(1)} mm`;$('#target-'+key).disabled=controller.held||controller.state==='release';}$$('[data-claw],[data-preset]').forEach(b=>b.disabled=controller.busy||controller.held);}
function updateControllerUI(){const c=controller,plan=c.activePlan&&c.state!=='ready'?c.activePlan:c.plan;const messages={ready:c.plan.valid?'Ready to grasp':'Outside reach',reach:'Reaching for target',close:'Closing the dactylus',lift:'Contact confirmed',hold:'Target held',release:'Releasing target',released:'Released · reset to place',recover:'Missed · recovering'};$('#grab-status').textContent=messages[c.state];$('#grab-hand').textContent=plan?.claw.side==='R'?'RIGHT CRUSHER':'LEFT CUTTER';$('#grab-state').textContent=c.state.toUpperCase();$('#reach-note').textContent=c.held?'Target supported between fixed and moving fingers.':c.state==='released'?'Reset to place the bead in front again.':c.plan.valid?'Within reach · drag to adjust placement.':c.plan.reason;$('#grab-button-text').textContent=c.held?'Release target':c.state==='released'?'Reset target':c.busy?'Grasping…':'Reach & grasp';$('#grab-button').disabled=!c.held&&c.state!=='released'&&(c.busy||!c.plan.valid);$('#grab-count').textContent=c.catches||c.misses?`${c.catches} GRIPS · ${c.misses} MISSES`:'CONTACT-BASED GRIP';$$('[data-phase]').forEach(el=>el.classList.toggle('active',el.dataset.phase===c.state||(el.dataset.phase==='hold'&&c.held)));syncFields();bead.position.copy(c.target);ring.position.copy(c.target);ring.quaternion.copy(camera.quaternion);ring.visible=!c.held;ring.material.color.set(c.plan.valid?'#a58b51':'#b67d67');tag.textContent=c.held?'GRIPPED':c.state==='released'?'RELEASED':'DRAG TARGET';tag.classList.toggle('held',c.held);const p=c.target.clone().project(camera);tag.style.left=`${Math.min(viewport.clientWidth-55,Math.max(55,(p.x+1)*viewport.clientWidth/2))}px`;tag.style.top=`${(1-p.y)*viewport.clientHeight/2}px`;tag.hidden=Math.abs(p.x)>1||Math.abs(p.y)>1;}
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta(),now=performance.now();if(document.hidden)return;if(tween){const t=Math.min(1,(now-tween.start)/450),u=t*t*(3-2*t);camera.position.lerpVectors(tween.p0,tween.p1,u);orbit.target.lerpVectors(tween.t0,tween.t1,u);if(t===1)tween=null;dirty=true;}orbit.update();if(rig&&!exporting){if(mode==='grab'){controller.update(paused?0:dt*speed);updateControllerUI();grid.material.uniforms.strength.value=.028;}else if(action){action.paused=paused;mixer.update(dt);const walking=current.startsWith('Walk_');grid.material.uniforms.strength.value=walking?.065:.028;grid.material.uniforms.travel.value=walking?(current==='Walk_Left'?-1:1)*(walkCycles*action.getClip().duration+action.time)*CRAB.walkSpeed*1000:0;if(walking)$('#viewport-mode').textContent=`SIDESTEP ${current==='Walk_Left'?'LEFT':'RIGHT'} · 10 MM/S`;if(now-lastUI>60){$('#scrubber').value=action.time;$('#current-time').textContent=action.time.toFixed(2).padStart(5,'0');const p=action.time/action.getClip().duration*100;$('#scrubber').style.background=`linear-gradient(to right,#849e7b ${p}%,#dce6d4 ${p}%)`;lastUI=now;}}}if(!paused||dirty||orbit.autoRotate){renderer.render(scene,camera);dirty=false;}}
load();animate();
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$$('[data-clip]').forEach(b=>b.addEventListener('click',()=>{paused=false;selectClip(b.dataset.clip);}));$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$$('[data-speed]').forEach(b=>b.addEventListener('click',()=>{speed=Number(b.dataset.speed);if(action)action.timeScale=speed;$('#speed-label').textContent=`${speed===.25?'.25':speed.toFixed(1)}×`;$$('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));}));
function togglePause(){paused=!paused;if(mode==='motion'&&!paused&&action?.time>=action.getClip().duration)action.reset().play();pauseIcon();dirty=true;}
$('#play-button').addEventListener('click',togglePause);$('#grab-pause').addEventListener('click',togglePause);$('#restart-button').addEventListener('click',()=>{paused=false;selectClip(current);});$('#scrubber').addEventListener('input',e=>{if(!action)return;paused=true;action.paused=false;action.time=Number(e.target.value);mixer.update(0);action.paused=true;pauseIcon();dirty=true;});
for(const key of ['x','y','z'])$('#target-'+key).addEventListener('input',e=>{controller?.setPlacement({[key]:Number(e.target.value)});syncFields();});
$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>{controller.setPlacement({x:Number(b.dataset.preset),y:20,z:54});syncFields();}));
$$('[data-claw]').forEach(b=>b.addEventListener('click',()=>{controller.selectSide(b.dataset.claw);$$('[data-claw]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});}));
$('#grab-button').addEventListener('click',()=>{controller.grab();paused=false;pauseIcon();});$('#reset-target').addEventListener('click',()=>{endDrag();controller.reset();syncFields();});$('#auto-grab').addEventListener('change',e=>{controller.auto=e.target.checked;if(e.target.checked){paused=false;pauseIcon();}});
for(const [id,fn] of [['rotate-toggle',on=>orbit.autoRotate=on],['wireframe-toggle',on=>materials.forEach(m=>m.wireframe=on)],['skeleton-toggle',on=>{if(skeleton)skeleton.visible=on;}]])$('#'+id).addEventListener('click',()=>{const el=$('#'+id),on=el.getAttribute('aria-pressed')!=='true';el.setAttribute('aria-pressed',on);el.classList.toggle('active',on);fn(on);dirty=true;});
$('#reset-camera').addEventListener('click',()=>{setView('perspective');orbit.autoRotate=false;$('#rotate-toggle').classList.remove('active');$('#rotate-toggle').setAttribute('aria-pressed','false');});$('#references-button').addEventListener('click',()=>$('#references-dialog').showModal());$('#close-references').addEventListener('click',()=>$('#references-dialog').close());
document.addEventListener('keydown',e=>{if(e.repeat||$('#references-dialog').open||document.activeElement.matches('input,textarea,select'))return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a'){e.preventDefault();paused=false;selectClip('Walk_Left');}if(e.key==='ArrowRight'||e.key.toLowerCase()==='d'){e.preventDefault();paused=false;selectClip('Walk_Right');}if(e.code==='Space'&&!document.activeElement.matches('button,a')){e.preventDefault();togglePause();}});
$('.download').addEventListener('click',()=>toast('GLB contains five clips. The target controller runs in the viewer.'));
const raycaster=new THREE.Raycaster(),plane=new THREE.Plane();function ray(e){const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);return raycaster.ray;}
function targetScreen(){const p=controller.target.clone().project(camera),r=renderer.domElement.getBoundingClientRect();return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};}
renderer.domElement.addEventListener('pointerdown',e=>{if(mode!=='grab'||!controller||controller.held||controller.state==='release'||e.button!==0||!ray(e).intersectsSphere(new THREE.Sphere(controller.target,TARGET_RADIUS*2.3)))return;e.preventDefault();e.stopImmediatePropagation();tween=null;const auto=orbit.autoRotate,damping=orbit.enableDamping;orbit.autoRotate=false;orbit.enableDamping=false;orbit.update();orbit.enabled=false;plane.setFromNormalAndCoplanarPoint(camera.getWorldDirection(V()),controller.target);const hit=ray(e).intersectPlane(plane,V());drag={id:e.pointerId,auto,damping,offset:controller.target.clone().sub(hit||controller.target)};renderer.domElement.setPointerCapture(e.pointerId);controller.dragging=true;renderer.domElement.style.cursor='grabbing';},true);
renderer.domElement.addEventListener('pointermove',e=>{if(!controller||mode!=='grab')return;if(drag&&e.pointerId===drag.id){e.preventDefault();e.stopImmediatePropagation();const p=ray(e).intersectPlane(plane,V());if(p){controller.setTarget(p.add(drag.offset));syncFields();dirty=true;}}else renderer.domElement.style.cursor=!controller.held&&ray(e).intersectsSphere(new THREE.Sphere(controller.target,TARGET_RADIUS*2.3))?'grab':'';},true);
function endDrag(){if(!drag)return;if(renderer.domElement.hasPointerCapture(drag.id))renderer.domElement.releasePointerCapture(drag.id);orbit.enabled=true;orbit.autoRotate=drag.auto;orbit.enableDamping=drag.damping;drag=null;controller.dragging=false;controller.changedAt=controller.time;renderer.domElement.style.cursor='';}
for(const event of ['pointerup','pointercancel'])renderer.domElement.addEventListener(event,e=>{if(drag&&e.pointerId===drag.id){e.preventDefault();e.stopImmediatePropagation();endDrag();}},true);window.addEventListener('blur',endDrag);
async function exportGLB(){if(!rig)throw new Error('The model is loading.');const oldPaused=paused,oldMode=mode,oldClip=current,oldTime=action?.time||0;exporting=true;paused=true;mixer.stopAllAction();rig.reset();model.updateMatrixWorld(true);try{return await new GLTFExporter().parseAsync(model,{binary:true,animations:clips,trs:true,onlyVisible:true,maxTextureSize:2048});}finally{exporting=false;paused=oldPaused;if(oldMode==='motion'){selectClip(oldClip);action.time=oldTime;}else controller.update(0);dirty=true;}}
