import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {createIcons,BookOpen,Download,Waves,Eye,Fingerprint,Rotate3d,Triangle,GitFork,Focus,Mouse,Pause,Play,SkipBack,X} from 'lucide';
import '../style.css';
import './frog.css';
const icons={BookOpen,Download,Waves,Eye,Fingerprint,Rotate3d,Triangle,GitFork,Focus,Mouse,Pause,Play,SkipBack,X};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],refresh=()=>createIcons({icons,attrs:{'aria-hidden':'true'}});refresh();
const viewport=$('#viewport'),building=new URLSearchParams(location.search).has('build');
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.84;viewport.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#efeee7');scene.fog=new THREE.Fog('#efeee7',.2,.6);
const camera=new THREE.PerspectiveCamera(36,1,.0005,3);camera.position.set(.082,.055,.106);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.013,.001);controls.enableDamping=true;controls.minDistance=.022;controls.maxDistance=.30;controls.maxPolarAngle=Math.PI*.49;controls.autoRotateSpeed=.45;
const room=new RoomEnvironment(),pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(room,.05).texture;scene.environment=environment;scene.environmentIntensity=.38;room.dispose();pmrem.dispose();
const sun=new THREE.DirectionalLight('#fff8e9',1.45);sun.position.set(-.075,.13,.07);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-.085,right:.085,top:.085,bottom:-.07,near:.005,far:.4});sun.shadow.normalBias=.00010;sun.shadow.bias=-.0002;sun.shadow.radius=4;scene.add(sun);
const fill=new THREE.DirectionalLight('#e3e9ee',.55);fill.position.set(.08,.06,-.06);scene.add(fill,new THREE.HemisphereLight('#f2f0e3','#a4a28b',.45));
const floor=new THREE.Mesh(new THREE.PlaneGeometry(2,2),new THREE.MeshStandardMaterial({color:'#e4e3da',roughness:.97}));floor.rotation.x=-Math.PI/2;floor.position.y=0;floor.receiveShadow=true;scene.add(floor);
let model,clips,mixer,action,helper,current='Idle',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,speed=1,dirty=true,tween=null;
const materials=new Set(),clock=new THREE.Clock();let uiTime=0,toastTimer,exporting=false;
controls.addEventListener('change',()=>dirty=true);document.addEventListener('click',()=>dirty=true);document.addEventListener('input',()=>dirty=true);document.addEventListener('visibilitychange',()=>clock.getDelta());
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2500);}
function playIcon(){$('#play-button').innerHTML=`<i data-lucide="${paused?'play':'pause'}"></i>`;$('#play-button').setAttribute('aria-label',paused?'Play animation':'Pause animation');refresh();}
function selectClip(name){if(!mixer)return;const clip=clips.find(c=>c.name===name);if(!clip)return;mixer.stopAllAction();current=name;action=mixer.clipAction(clip).reset();action.setLoop(name==='Idle'?THREE.LoopRepeat:THREE.LoopOnce,name==='Idle'?Infinity:1);action.clampWhenFinished=true;action.timeScale=speed;action.play();action.paused=paused;$$('[data-clip]').forEach(b=>{b.classList.toggle('active',b.dataset.clip===name);b.setAttribute('aria-pressed',b.dataset.clip===name);});$('#current-clip').textContent=name==='Idle'?'Rest & breathe':'Blink';$('#clip-description').textContent=name==='Idle'?'Quiet throat movement and a natural resting pose':'A short eyelid movement study';$('#clip-type').textContent=name==='Idle'?'RESTING LOOP':'EYELID STUDY';$('#scrubber').max=clip.duration;$('#total-time').textContent=clip.duration.toFixed(2).padStart(5,'0');$('.timeline-ticks').innerHTML=Array.from({length:7},(_,i)=>`<span>${Number((clip.duration*i/6).toFixed(1))}${i===6?' s':''}</span>`).join('');playIcon();dirty=true;}
async function load(){try{if(building){const {createFrog}=await import('./model.js');const asset=createFrog();model=asset.root;clips=asset.clips;}else{const asset=await new GLTFLoader().loadAsync('/models/frog.glb');model=asset.scene;clips=asset.animations;}scene.add(model);let triangles=0,bones=0;model.traverse(o=>{if(o.isBone)bones++;if(o.isMesh){o.castShadow=o.receiveShadow=true;o.frustumCulled=false;triangles+=o.geometry.index?o.geometry.index.count/3:o.geometry.attributes.position.count/3;materials.add(o.material);if(o.material.map)o.material.map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());}});$('#triangle-count').textContent=`${(triangles/1000).toFixed(1)}k triangles`;$('#bone-count').textContent=`${bones} bones`;helper=new THREE.SkeletonHelper(model);helper.material.depthTest=false;helper.renderOrder=12;helper.visible=false;scene.add(helper);mixer=new THREE.AnimationMixer(model);mixer.addEventListener('finished',()=>{paused=true;playIcon();dirty=true;});selectClip('Idle');$('#loading').classList.add('hidden');window.frog={model,clips,mixer,renderer,scene,camera,controls,stats:{triangles,bones},selectClip,exportGLB,poseAt(name,time){paused=true;selectClip(name);action.paused=false;action.time=time;mixer.update(0);action.paused=true;model.updateMatrixWorld(true);renderer.render(scene,camera);dirty=true;}};window.frogReady=true;}catch(error){console.error(error);window.frogError=error.message;$('#loading').innerHTML='<span>The frog could not load.</span><small>Please reload the page.</small>';}}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=w/h<1?48:36;camera.updateProjectionMatrix();dirty=true;}new ResizeObserver(resize).observe(viewport);resize();
function setView(name){const views={perspective:{p:[.082,.055,.106],t:[0,.013,.001]},front:{p:[0,.034,.139],t:[0,.013,.002]},side:{p:[.132,.037,.01],t:[0,.012,.001]},top:{p:[.001,.15,.001],t:[0,.01,0]},face:{p:[.034,.031,.076],t:[0,.023,.023]}};const v=views[name];if(!v)return;tween={start:performance.now(),p0:camera.position.clone(),p1:new THREE.Vector3(...v.p),t0:controls.target.clone(),t1:new THREE.Vector3(...v.t)};$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));dirty=true;}
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta(),now=performance.now();if(document.hidden)return;if(mixer&&!exporting){action.paused=paused;mixer.update(dt);}if(tween){const t=Math.min(1,(now-tween.start)/500),u=t*t*(3-2*t);camera.position.lerpVectors(tween.p0,tween.p1,u);controls.target.lerpVectors(tween.t0,tween.t1,u);if(t===1)tween=null;dirty=true;}controls.update();if(!paused||dirty||controls.autoRotate){renderer.render(scene,camera);dirty=false;}if(action&&now-uiTime>65){$('#scrubber').value=action.time;$('#current-time').textContent=action.time.toFixed(2).padStart(5,'0');const p=action.time/action.getClip().duration*100;$('#scrubber').style.background=`linear-gradient(to right,#92967a ${p}%,#dfe2d2 ${p}%)`;uiTime=now;}}
load();animate();
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-clip]').forEach(b=>b.addEventListener('click',()=>{paused=false;selectClip(b.dataset.clip);}));
$$('[data-speed]').forEach(b=>b.addEventListener('click',()=>{speed=Number(b.dataset.speed);if(action)action.timeScale=speed;$('#speed-label').textContent=`${speed===.25?'0.25':speed.toFixed(1)}×`;$$('[data-speed]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});}));
$('#play-button').addEventListener('click',()=>{if(!action)return;paused=!paused;if(!paused&&action.time>=action.getClip().duration)action.reset().play();playIcon();});$('#restart-button').addEventListener('click',()=>{paused=false;selectClip(current);});
$('#scrubber').addEventListener('input',e=>{if(!action)return;paused=true;action.paused=false;action.time=Number(e.target.value);mixer.update(0);action.paused=true;playIcon();dirty=true;});
for(const [id,fn] of [['rotate-toggle',on=>controls.autoRotate=on],['wireframe-toggle',on=>materials.forEach(m=>m.wireframe=on)],['skeleton-toggle',on=>{if(helper)helper.visible=on;}]])$('#'+id).addEventListener('click',()=>{const b=$('#'+id),on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',on);b.classList.toggle('active',on);fn(on);dirty=true;});
$('#reset-camera').addEventListener('click',()=>{setView('perspective');controls.autoRotate=false;$('#rotate-toggle').setAttribute('aria-pressed','false');$('#rotate-toggle').classList.remove('active');});
const palette={Earth:{tint:'#ffffff',chip:'#827764',label:'EARTH / OLIVE-BROWN + IVORY'},Stone:{tint:'#c8cbd0',chip:'#96978e',label:'STONE / COOL GREY + WARM IVORY'},Olive:{tint:'#cbd0b8',chip:'#818473',label:'OLIVE / MUTED MOSS + IVORY'}};
$$('[data-palette]').forEach(b=>b.addEventListener('click',()=>{const p=palette[b.dataset.palette];materials.forEach(m=>{if(['Skin','Dorsolateral folds','Eyelids'].includes(m.name))m.color.set(p.tint);});$$('[data-palette]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});$('#palette-name').textContent=b.dataset.palette.toUpperCase();$('#colour-caption').textContent=p.label;$('.colour-chip').style.background=p.chip;dirty=true;}));
$('#references-button').addEventListener('click',()=>$('#references-dialog').showModal());$('#close-references').addEventListener('click',()=>$('#references-dialog').close());
$('#references-dialog').addEventListener('click',e=>{if(e.target===$('#references-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
document.addEventListener('keydown',e=>{if(e.repeat||$('#references-dialog').open||document.activeElement.matches('input,button,a,textarea,select'))return;if(e.code==='Space'){e.preventDefault();$('#play-button').click();}if(e.key==='1'||e.key==='2'){paused=false;selectClip(e.key==='1'?'Idle':'Blink');}});
$('.download').addEventListener('click',e=>{if(building){e.preventDefault();exportGLB().then(buffer=>{const url=URL.createObjectURL(new Blob([buffer],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download='frontier-neutral-frog.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});}else toast('Downloading the neutral base colourway with both animation clips.');});
async function exportGLB(){if(!model)throw new Error('Model is still loading.');const before=paused,name=current,time=action.time;paused=true;exporting=true;mixer.stopAllAction();model.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.pose();if(o.morphTargetInfluences)o.morphTargetInfluences.fill(0);});model.updateMatrixWorld(true);try{return await new GLTFExporter().parseAsync(model,{binary:true,animations:clips,onlyVisible:true,trs:true,maxTextureSize:2048});}finally{exporting=false;paused=before;selectClip(name);action.time=time;dirty=true;}}
