"""Blender object name -> engineering name, per vehicle.
Classes: BODY (exterior main body, in scope), GLASS (in scope, drawn as body),
AERO, WHEEL, INT, LOWPOLY (shrinkwrap working copy of a BODY part), HELPER."""

QUICKSILVER = {
    'TrailingBody.Guide':   ('Body_Main_Shell', 'BODY'),
    'TrailingBody':         ('Body_Main_Shell_LowPoly', 'LOWPOLY'),
    'Lead-Body':            ('Body_Front_Clip', 'BODY'),
    'TrailingBody.001':     ('Body_Door_Skin', 'BODY'),
    'Final Body Guide.004': ('Body_Door_Pillar_Frame', 'BODY'),
    'Final Body Guide.005': ('Body_Side_Intake_Scoop', 'BODY'),
    'TrailingBody.002':     ('Body_Rear_Deck', 'BODY'),
    'TrailingBody.006':     ('Body_Rear_Deck_Louvres', 'BODY'),
    'TrailingBody.007':     ('Body_Rear_Deck_Lip', 'BODY'),
    'TrailingBody.008':     ('Body_Rear_Header_Lip', 'BODY'),
    'TrailingBody.003':     ('Body_Window_Surround', 'BODY'),
    'TrailingBody.004':     ('Glass_Roof_Scoop', 'GLASS'),
    'TrailingBody.005':     ('Glass_Windscreen', 'GLASS'),
    'LeadEdge.002':         ('Body_Front_Bumper_Lower', 'BODY'),
    'LeadEdge':             ('Body_Sill_Rail', 'BODY'),
    'LeadEdge.001':         ('Body_Front_Lip', 'BODY'),
    'Front Header':         ('Body_Front_Grille_Frame', 'BODY'),
    'FuelPanel':            ('Body_Fuel_Door', 'BODY'),
    'Exterior02.003':       ('Body_Rear_Deck_Vent', 'BODY'),
    'Exterior02.002':       ('Aero_Rear_Diffuser_Fence', 'AERO'),
    'Exterior02.004':       ('Aero_Front_Splitter_End', 'AERO'),
    'RearSpoilers':         ('Aero_Rear_Wing', 'AERO'),
    'RearSpoilers.005':     ('Aero_Wing_Endplates', 'AERO'),
    'Aero-Mount':           ('Aero_Wing_Mount', 'AERO'),
    'Cylinder':             ('Aero_Wing_Pivot', 'AERO'),
    'StandardTyre.001':     ('Wheel_Rear', 'WHEEL'),
    'StandardTyre.004':     ('Wheel_Front', 'WHEEL'),
    'G3':                   ('Helper_Points', 'HELPER'),
    'G3.002':               ('Helper_Points_2', 'HELPER'),
    'G3.003':               ('Helper_Points_3', 'HELPER'),
    'Cube.001':             ('Helper_Cube', 'HELPER'),
}

EGOIST = {
    'GuideSurface.005': ('Body_Main_Shell', 'BODY'),
    'GuideSurface.004': ('Body_Door_Pillar_Frame', 'BODY'),
    'GuideSurface.007': ('Body_Door_Window_Frame', 'BODY'),
    'GuideSurface.008': ('Body_Door_Skin', 'BODY'),
    'GuideSurface.010': ('Body_Door_Skin_Lower', 'BODY'),
    'GuideSurface.009': ('Body_Side_Intake', 'BODY'),
    'GuideSurface.001': ('Glass_Roof_Panel', 'GLASS'),
    'Guide.011':        ('Glass_Windscreen', 'GLASS'),
    'Guide.002':        ('Glass_Rear_Window', 'GLASS'),
    'Guide.001':        ('Body_Cowl', 'BODY'),
    'Guide.016':        ('Body_Rear_Deck', 'BODY'),
    'Guide.005':        ('Body_Bonnet_Vent', 'BODY'),
    'Guide.012':        ('Body_Bonnet_Vent_2', 'BODY'),
    'Guide.014':        ('Body_Bonnet_Vent_3', 'BODY'),
    'Circle.003':       ('Body_Roof_Scoop', 'BODY'),
    'Circle.004':       ('Body_Rear_Scoop', 'BODY'),
    'Circle.007':       ('Body_Roof_Scoop_Inner', 'BODY'),
    'Guide.013':        ('Interior_Tub', 'INT'),
    'Circle.010':       ('Interior_Steering_Wheel', 'INT'),
    'Cube.004':         ('Interior_Dash', 'INT'),
    'Cube.005':         ('Interior_Mirror', 'INT'),
    'Cube.006':         ('Interior_Pedals', 'INT'),
    'Cube.011':         ('Interior_Column', 'INT'),
    'Plane.030':        ('Interior_Seat', 'INT'),
    'Plane.032':        ('Interior_Mirror_Housing', 'INT'),
    'SteeringWheel.002':('Interior_Steering_Wheel_2', 'INT'),
    'SpectatorCam':     ('Interior_Camera', 'INT'),
    'SpectatorCam.001': ('Interior_Camera_2', 'INT'),
    'FrontAero':        ('Aero_Front_Splitter', 'AERO'),
    'RearAero.001':     ('Aero_Diffuser', 'AERO'),
    'RearAero.002':     ('Aero_Undertray', 'AERO'),
    'RearAero.003':     ('Aero_Diffuser_Fence', 'AERO'),
    'SideSkirt':        ('Aero_Side_Skirt', 'AERO'),
    'Spoiler':          ('Aero_Rear_Wing', 'AERO'),
    'Fins':             ('Aero_Fins', 'AERO'),
    'Circle.050':       ('Aero_Wing_Mount', 'AERO'),
    'Circle.047':       ('Aero_Side_Blade', 'AERO'),
    'StandardTyre.002': ('Wheel_Spare', 'WHEEL'),
    'StandardTyre.007': ('Wheel_Front', 'WHEEL'),
    'StandardTyre.008': ('Wheel_Rear', 'WHEEL'),
    'Cylinder.007':     ('Wheel_Rim_Rear', 'WHEEL'),
    'Cylinder.008':     ('Wheel_Rim_Front', 'WHEEL'),
    'Cylinder.017':     ('Wheel_Rim_Spare', 'WHEEL'),
    'FF':               ('Wheel_Arch_Liner', 'WHEEL'),
    'Cube.001':         ('Helper_Cube', 'HELPER'),
}

LIGER = {
    'Body.001':             ('Body_Main_Shell', 'BODY'),
    'Body.004':             ('Body_Front_Cowl', 'BODY'),
    'ExteriorAssembly.001': ('Body_Roof_Glass_Frame', 'BODY'),
    'Plane.030':            ('Interior_Seats', 'INT'),
    'Plane.004':            ('Interior_Tub', 'INT'),
    'Final Body Guide.001': ('Interior_Console', 'INT'),
    'Final Body Guide.003': ('Interior_Dash_Top', 'INT'),
    'Final Body Guide.005': ('Interior_Dash', 'INT'),
    'Guide.004':            ('Interior_Mirror', 'INT'),
    'Cylinder.003':         ('Wheel_Rims', 'WHEEL'),
    'StandardTyre.001':     ('Wheel_Front', 'WHEEL'),
    'StandardTyre.002':     ('Wheel_Rear', 'WHEEL'),
    'RearFenders':          ('Aero_Rear_Fender_Flare', 'AERO'),
    'Sideskirts':           ('Aero_Side_Skirt', 'AERO'),
    'Spoilers':             ('Aero_Rear_Wing', 'AERO'),
    'Circle.001':           ('Aero_Roof_Fin', 'AERO'),
    'Circle.017':           ('Aero_Front_Splitter', 'AERO'),
    'Circle.018':           ('Aero_Front_Lip', 'AERO'),
}

CARS = {'Quicksilver': QUICKSILVER, 'Egoist': EGOIST, 'Liger': LIGER}
IN_SCOPE = ('BODY', 'GLASS')
