import assert from 'node:assert/strict';
import fs from 'node:fs';
import {launchBrowser} from './browser.mjs';
const browser=await launchBrowser(),errors=[];
try{
  const page=await browser.newPage({viewport:{width:1365,height:950},deviceScaleFactor:1,reducedMotion:'reduce'});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>window.mantisReady||window.mantisError,null,{timeout:90000});
  assert.equal(await page.evaluate(()=>window.mantisError),undefined);
  assert.equal(await page.evaluate(()=>window.mantis.mode),'hunt');
  assert(await page.locator('#hunt-timeline').isVisible());
  assert(!(await page.locator('#clip-timeline').isVisible()));
  await page.waitForFunction(()=>Math.abs(window.mantis.camera.position.z-.126)<.0001);
  // Real pointer drag: move the bead, not the orbit camera. No test-only setter.
  const before=await page.evaluate(()=>({camera:window.mantis.camera.position.toArray(),target:window.mantis.hunt.simulation.target.toArray(),screen:window.mantis.hunt.screenTarget()}));
  await page.mouse.move(before.screen.x,before.screen.y);await page.mouse.down();
  assert.equal(await page.evaluate(()=>window.mantis.controls.enabled),false);
  await page.mouse.move(before.screen.x+37,before.screen.y-19,{steps:5});await page.mouse.up();
  const after=await page.evaluate(()=>({camera:window.mantis.camera.position.toArray(),target:window.mantis.hunt.simulation.target.toArray(),enabled:window.mantis.controls.enabled,dragging:window.mantis.hunt.simulation.dragging}));
  assert(after.enabled&&!after.dragging);
  assert(Math.hypot(...after.target.map((v,i)=>v-before.target[i]))>.001);
  assert(Math.hypot(...after.camera.map((v,i)=>v-before.camera[i]))<1e-7);
  // Native keyboard range input, reach warning and safe rejection.
  await page.locator('#target-distance').focus();await page.keyboard.press('End');
  await page.waitForFunction(()=>!window.mantis.hunt.simulation.reach.reachable);
  assert(await page.locator('#hunt-command').isDisabled());
  await page.locator('[data-target-preset="0"]').click();
  await page.waitForFunction(()=>window.mantis.hunt.simulation.reach.reachable);
  await page.locator('#hunt-command').click();
  await page.waitForFunction(()=>window.mantis.hunt.simulation.phase==='holding',null,{timeout:30000});
  const held=await page.evaluate(()=>({status:window.mantis.hunt.simulation.status,contact:window.mantis.hunt.simulation.lastContact.hit}));
  assert.equal(held.status.captures,1);assert(held.contact);
  assert.equal(await page.locator('#hunt-command-text').innerText(),'Release target');
  assert(await page.locator('#target-angle').isDisabled());
  await page.locator('#hunt-command').click();
  await page.waitForFunction(()=>window.mantis.hunt.simulation.phase==='released',null,{timeout:20000});
  assert.equal(await page.locator('#hunt-command-text').innerText(),'Reset target');
  await page.locator('#hunt-reset').click();
  await page.waitForFunction(()=>!window.mantis.hunt.simulation.holding);
  assert(!(await page.locator('#target-angle').isDisabled()));
  // Mode change cancels drag and leaves the four existing clips usable.
  await page.locator('[data-mode="clips"]').click();
  assert.equal(await page.evaluate(()=>window.mantis.mode),'clips');
  assert(await page.locator('#clip-timeline').isVisible());
  assert.equal(await page.evaluate(()=>window.mantis.hunt.group.visible),false);
  await page.locator('[data-clip="Stance"]').click();
  await page.evaluate(()=>window.mantis.poseAt('Stance',1.2));
  assert((await page.evaluate(()=>window.mantis.model.getObjectByName('Hindwing_membrane').morphTargetInfluences[0]))>.97);
  await page.locator('[data-mode="hunt"]').click();
  await page.locator('#hunt-auto').check();
  await page.waitForFunction(()=>window.mantis.hunt.simulation.phase==='holding',null,{timeout:30000});
  assert((await page.evaluate(()=>window.mantis.hunt.simulation.captures))>=2);
  await page.locator('#hunt-auto').uncheck();
  await page.locator('#hunt-reset').click();
  await page.evaluate(()=>window.mantis.setPaused(true));
  await page.locator('#hunt-guides').uncheck();
  assert.equal(await page.evaluate(()=>window.mantis.hunt.showGuides),false);
  await page.locator('#hunt-guides').check();
  fs.mkdirSync('.screenshots/hunt',{recursive:true});
  await page.screenshot({path:'.screenshots/hunt/tested-desktop.png',timeout:90000,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});
  assert(await page.locator('#hunt-command').isVisible());
  assert(await page.locator('#target-distance').isVisible());
  const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(size.scroll<=size.width+1);
  await page.screenshot({path:'.screenshots/hunt/tested-mobile.png',timeout:90000,fullPage:true,animations:'disabled'});
  assert.deepEqual(errors,[]);
  console.log('PASS: real gizmo drag, orbit isolation, keyboard sliders, range rejection, lock/lean/grip, release, reset, clip mode, automatic strike, guides and mobile layout.');
}finally{await browser.close();}
