import { defaultSandLayer } from "./materialProfiles.js";

export function granularCatalog() {
  const base = {
    flakes: 0,
    coat: 0,
    coatRoughness: 0.5,
    depth: 0.5,
    sheen: 0,
    anisotropy: 0,
    previewShape: "Panel",
    grain: 0.2,
    weaveAngle: 90,
  };
  return [
    {
      ...base,
      id: "corrugated-zinc",
      name: "Corrugated Zinc",
      category: "Metal",
      type: 21,
      recipeId: "corrugatedZinc",
      label: "ZINC SHEET · ROUNDED SHEET",
      color: "#c6d0d4",
      colors: ["#c6d0d4"],
      roughness: 0.34,
      metalness: 1,
      detailScale: 2.2,
      ribDepth: 0.14,
      ribProfile: 0,
      sheetFinish: 1,
      sheetOxidation: 0.16,
      sheetSpangle: 0.3,
      description:
        "Rounded corrugation over a zinc-sheet finish. Rib normals and zinc spangle and mild weathering; not a structural roofing specification.",
    },
    {
      ...base,
      id: "corrugated-steel",
      name: "Corrugated Steel",
      category: "Metal",
      type: 21,
      recipeId: "corrugatedSteel",
      label: "GALVANISED STEEL · GARAGE / IBR",
      color: "#b5c0c2",
      colors: ["#b5c0c2"],
      roughness: 0.4,
      metalness: 1,
      detailScale: 1.65,
      ribDepth: 0.2,
      ribProfile: 1,
      sheetFinish: 2,
      sheetOxidation: 0.06,
      sheetSpangle: 0.65,
      description:
        "Zinc-coated garage / cladding sheet with a trapezoidal IBR-style rib profile, spangle variation and optional weathering. Round and roller-door profiles are also selectable.",
    },
    {
      ...base,
      id: "sand",
      name: "Sand",
      category: "Nature",
      type: 37,
      recipeId: "sand",
      label: "INDIVIDUAL MINERAL GRAINS",
      color: "#c9aa79",
      secondaryColor: "#eee2c7",
      colors: ["#c9aa79", "#eee2c7"],
      roughness: 0.88,
      metalness: 0,
      grainSize: 0.7,
      grainSizeVariation: 0.55,
      grainRoughness: 0.58,
      grainRoughnessVariation: 0.3,
      grainSpecular: 0.8,
      grainSpecularVariation: 0.35,
      grainIOR: 1.544,
      grainRoundness: 0.45,
      grainTilt: 0.32,
      grainRelief: 0.85,
      sandCoverage: 1,
      sandScale: 1,
      surfaceSeed: 41,
      description:
        "Seeded, differently sized mineral grains with individual facet direction, color, roughness and dielectric specular response. Close-up grain relief is procedural, not metallic flakes or particle geometry.",
    },
    {
      ...base,
      id: "layered-sand",
      name: "Layered Sand",
      category: "Nature",
      type: 38,
      recipeId: "layeredSand",
      label: "EDITABLE SAND BEDS / STRATA",
      color: "#a98759",
      colors: ["#d8c199", "#a98759", "#e5d6b9"],
      roughness: 0.88,
      metalness: 0,
      sandScale: 1,
      sandArrangement: "beds",
      sandBandFrequency: 1.5,
      sandBandWarp: 0.22,
      sandBandAngle: 0,
      surfaceSeed: 63,
      sandLayers: [
        {
          ...defaultSandLayer(0),
          name: "Quartz-rich surface",
          color: "#d8c199",
          secondaryColor: "#f0e7d4",
          size: 0.65,
          roughness: 0.42,
          specular: 0.95,
          coverage: 0.85,
        },
        {
          ...defaultSandLayer(1),
          name: "Fine pale bed",
          color: "#e5d6b9",
          secondaryColor: "#fbf3df",
          size: 0.25,
          roughness: 0.78,
          specular: 0.55,
          coverage: 0.92,
          thickness: 0.7,
        },
        {
          ...defaultSandLayer(2),
          name: "Coarse warm bed",
          color: "#a98759",
          secondaryColor: "#d4b180",
          size: 0.95,
          roughness: 0.65,
          specular: 0.75,
          coverage: 1,
          thickness: 1.3,
        },
      ],
      description:
        "Up to four editable grain beds, each with its own color, grain size distribution, specular, roughness and relief. Composite grains top-to-bottom or show wavy sediment bands.",
    },
  ];
}
